version: "3.5"
services:
  bdd_triangulo_mvn:
    image: maven:3.6-jdk-8
    container_name: bdd_triangulo_mvn
    command: /bin/sh -c "rm -R target -f && mvn package"
    volumes:
      - ./:/var/app
    working_dir: /var/app